meta_product_name: "Singytalkie"
meta_title: "Singytalkie - Learn singing!"
meta_description: "Singytalkie makes learning a new language fun! You can choose a song, and learn it's lyrics by listening, filling in the blanks and learning the translation. When you lack motivation you can always pick a song and sing!"
